### ISSUE TITLE
fshs.sys loaded twice at different attitude?

### ISSUE THREAD

**Issue by CaledoniaProject** [D3VI5H4/Antivirus-Artifacts#3]
I'm seeing a duplicated entry in this table:

![screen 2020-12-28 at 19 54 21](https://user-images.githubusercontent.com/1357701/103212713-8aca8a80-4946-11eb-9c8f-8b1d292d0ee2.jpg)

Is fshs.sys supposed to load twice at different attitude?

**Comment by ethereal-vx** [comment]
Nope. This is indeed the fshs.sys file attitudes. You can see them both listed on MSDN as well here: https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/allocated-altitudes#360000---389999-fsfilter-activity-monitor
